title: "CtRL-Sim: Reactive and Controllable Driving Agents with Offline Reinforcement Learning"
description: A framework that leverages offline reinforcement learning for controllable closed-loop simulation.<br>Work by <a href="https://github.com/RLuke22">Luke Rowe</a>, <a href="https://mila.quebec/en/person/roger-girgis/">Roger Girgis</a>, <a href="https://www.linkedin.com/in/anthony-gosselin-098b7a1a1/?originalSubdomain=ca">Anthony Gosselin</a>, <a href="https://mila.quebec/en/person/bruno-carrez/">Bruno Carrez</a>, <a href="https://fgolemo.github.io/">Florian Golemo</a>, <a href="https://www.cs.princeton.edu/~fheide/">Felix Heide<a/>, <a href="https://liampaull.ca/">Liam Paull</a>, <a href="https://sites.google.com/view/christopher-pal">Christopher Pal</a>
theme: jekyll-theme-cayman
links:
  arxiv: https://arxiv.org/abs/2403.19918
  code: https://github.com/montrealrobotics/ctrl-sim/
# sass:
#   sass_dir: _sass